// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFdd-G8wVfIfudr3VCnqBkV7Iu5VYR1M',
    appId: '1:618624814273:web:e9b646fcd04795cdf31840',
    messagingSenderId: '618624814273',
    projectId: 'auth-841db',
    authDomain: 'auth-841db.firebaseapp.com',
    storageBucket: 'auth-841db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2cAtTiLfRG-azFXP2-3m5oUt24Pqsos',
    appId: '1:618624814273:android:509e4e9a4281da88f31840',
    messagingSenderId: '618624814273',
    projectId: 'auth-841db',
    storageBucket: 'auth-841db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDbMKvndiPj_iCczGILCBLIqcJyfdC8Y8',
    appId: '1:618624814273:ios:ebaddea63eae9148f31840',
    messagingSenderId: '618624814273',
    projectId: 'auth-841db',
    storageBucket: 'auth-841db.appspot.com',
    iosBundleId: 'com.example.unsaidFeelings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDbMKvndiPj_iCczGILCBLIqcJyfdC8Y8',
    appId: '1:618624814273:ios:545f2f97b80f1481f31840',
    messagingSenderId: '618624814273',
    projectId: 'auth-841db',
    storageBucket: 'auth-841db.appspot.com',
    iosBundleId: 'com.example.unsaidFeelings.RunnerTests',
  );
}
